/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.carcattone_data.Coord', null, global);
goog.exportSymbol('proto.carcattone_data.Coord1D', null, global);
goog.exportSymbol('proto.carcattone_data.Coord2D', null, global);
goog.exportSymbol('proto.carcattone_data.Coord3D', null, global);
goog.exportSymbol('proto.carcattone_data.Hex', null, global);
goog.exportSymbol('proto.carcattone_data.HexType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carcattone_data.Coord1D = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.carcattone_data.Coord1D, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.carcattone_data.Coord1D.displayName = 'proto.carcattone_data.Coord1D';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carcattone_data.Coord1D.prototype.toObject = function(opt_includeInstance) {
  return proto.carcattone_data.Coord1D.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carcattone_data.Coord1D} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carcattone_data.Coord1D.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carcattone_data.Coord1D}
 */
proto.carcattone_data.Coord1D.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carcattone_data.Coord1D;
  return proto.carcattone_data.Coord1D.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carcattone_data.Coord1D} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carcattone_data.Coord1D}
 */
proto.carcattone_data.Coord1D.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carcattone_data.Coord1D.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carcattone_data.Coord1D.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carcattone_data.Coord1D} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carcattone_data.Coord1D.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.carcattone_data.Coord1D.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.carcattone_data.Coord1D.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carcattone_data.Coord2D = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.carcattone_data.Coord2D, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.carcattone_data.Coord2D.displayName = 'proto.carcattone_data.Coord2D';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carcattone_data.Coord2D.prototype.toObject = function(opt_includeInstance) {
  return proto.carcattone_data.Coord2D.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carcattone_data.Coord2D} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carcattone_data.Coord2D.toObject = function(includeInstance, msg) {
  var f, obj = {
    row: jspb.Message.getFieldWithDefault(msg, 1, 0),
    column: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carcattone_data.Coord2D}
 */
proto.carcattone_data.Coord2D.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carcattone_data.Coord2D;
  return proto.carcattone_data.Coord2D.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carcattone_data.Coord2D} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carcattone_data.Coord2D}
 */
proto.carcattone_data.Coord2D.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRow(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setColumn(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carcattone_data.Coord2D.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carcattone_data.Coord2D.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carcattone_data.Coord2D} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carcattone_data.Coord2D.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRow();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getColumn();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 row = 1;
 * @return {number}
 */
proto.carcattone_data.Coord2D.prototype.getRow = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.carcattone_data.Coord2D.prototype.setRow = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 column = 2;
 * @return {number}
 */
proto.carcattone_data.Coord2D.prototype.getColumn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.carcattone_data.Coord2D.prototype.setColumn = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carcattone_data.Coord3D = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.carcattone_data.Coord3D, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.carcattone_data.Coord3D.displayName = 'proto.carcattone_data.Coord3D';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carcattone_data.Coord3D.prototype.toObject = function(opt_includeInstance) {
  return proto.carcattone_data.Coord3D.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carcattone_data.Coord3D} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carcattone_data.Coord3D.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: jspb.Message.getFieldWithDefault(msg, 1, 0),
    y: jspb.Message.getFieldWithDefault(msg, 2, 0),
    z: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carcattone_data.Coord3D}
 */
proto.carcattone_data.Coord3D.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carcattone_data.Coord3D;
  return proto.carcattone_data.Coord3D.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carcattone_data.Coord3D} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carcattone_data.Coord3D}
 */
proto.carcattone_data.Coord3D.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setZ(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carcattone_data.Coord3D.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carcattone_data.Coord3D.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carcattone_data.Coord3D} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carcattone_data.Coord3D.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getY();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getZ();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int32 x = 1;
 * @return {number}
 */
proto.carcattone_data.Coord3D.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.carcattone_data.Coord3D.prototype.setX = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 y = 2;
 * @return {number}
 */
proto.carcattone_data.Coord3D.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.carcattone_data.Coord3D.prototype.setY = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 z = 3;
 * @return {number}
 */
proto.carcattone_data.Coord3D.prototype.getZ = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.carcattone_data.Coord3D.prototype.setZ = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carcattone_data.Coord = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.carcattone_data.Coord, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.carcattone_data.Coord.displayName = 'proto.carcattone_data.Coord';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carcattone_data.Coord.prototype.toObject = function(opt_includeInstance) {
  return proto.carcattone_data.Coord.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carcattone_data.Coord} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carcattone_data.Coord.toObject = function(includeInstance, msg) {
  var f, obj = {
    coord1d: (f = msg.getCoord1d()) && proto.carcattone_data.Coord1D.toObject(includeInstance, f),
    coord2d: (f = msg.getCoord2d()) && proto.carcattone_data.Coord2D.toObject(includeInstance, f),
    coord3d: (f = msg.getCoord3d()) && proto.carcattone_data.Coord3D.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carcattone_data.Coord}
 */
proto.carcattone_data.Coord.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carcattone_data.Coord;
  return proto.carcattone_data.Coord.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carcattone_data.Coord} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carcattone_data.Coord}
 */
proto.carcattone_data.Coord.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.carcattone_data.Coord1D;
      reader.readMessage(value,proto.carcattone_data.Coord1D.deserializeBinaryFromReader);
      msg.setCoord1d(value);
      break;
    case 2:
      var value = new proto.carcattone_data.Coord2D;
      reader.readMessage(value,proto.carcattone_data.Coord2D.deserializeBinaryFromReader);
      msg.setCoord2d(value);
      break;
    case 3:
      var value = new proto.carcattone_data.Coord3D;
      reader.readMessage(value,proto.carcattone_data.Coord3D.deserializeBinaryFromReader);
      msg.setCoord3d(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carcattone_data.Coord.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carcattone_data.Coord.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carcattone_data.Coord} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carcattone_data.Coord.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCoord1d();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.carcattone_data.Coord1D.serializeBinaryToWriter
    );
  }
  f = message.getCoord2d();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.carcattone_data.Coord2D.serializeBinaryToWriter
    );
  }
  f = message.getCoord3d();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.carcattone_data.Coord3D.serializeBinaryToWriter
    );
  }
};


/**
 * optional Coord1D coord1D = 1;
 * @return {?proto.carcattone_data.Coord1D}
 */
proto.carcattone_data.Coord.prototype.getCoord1d = function() {
  return /** @type{?proto.carcattone_data.Coord1D} */ (
    jspb.Message.getWrapperField(this, proto.carcattone_data.Coord1D, 1));
};


/** @param {?proto.carcattone_data.Coord1D|undefined} value */
proto.carcattone_data.Coord.prototype.setCoord1d = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.carcattone_data.Coord.prototype.clearCoord1d = function() {
  this.setCoord1d(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.carcattone_data.Coord.prototype.hasCoord1d = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Coord2D coord2D = 2;
 * @return {?proto.carcattone_data.Coord2D}
 */
proto.carcattone_data.Coord.prototype.getCoord2d = function() {
  return /** @type{?proto.carcattone_data.Coord2D} */ (
    jspb.Message.getWrapperField(this, proto.carcattone_data.Coord2D, 2));
};


/** @param {?proto.carcattone_data.Coord2D|undefined} value */
proto.carcattone_data.Coord.prototype.setCoord2d = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.carcattone_data.Coord.prototype.clearCoord2d = function() {
  this.setCoord2d(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.carcattone_data.Coord.prototype.hasCoord2d = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Coord3D coord3D = 3;
 * @return {?proto.carcattone_data.Coord3D}
 */
proto.carcattone_data.Coord.prototype.getCoord3d = function() {
  return /** @type{?proto.carcattone_data.Coord3D} */ (
    jspb.Message.getWrapperField(this, proto.carcattone_data.Coord3D, 3));
};


/** @param {?proto.carcattone_data.Coord3D|undefined} value */
proto.carcattone_data.Coord.prototype.setCoord3d = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.carcattone_data.Coord.prototype.clearCoord3d = function() {
  this.setCoord3d(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.carcattone_data.Coord.prototype.hasCoord3d = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carcattone_data.Hex = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.carcattone_data.Hex, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.carcattone_data.Hex.displayName = 'proto.carcattone_data.Hex';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carcattone_data.Hex.prototype.toObject = function(opt_includeInstance) {
  return proto.carcattone_data.Hex.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carcattone_data.Hex} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carcattone_data.Hex.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    coord: (f = msg.getCoord()) && proto.carcattone_data.Coord.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carcattone_data.Hex}
 */
proto.carcattone_data.Hex.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carcattone_data.Hex;
  return proto.carcattone_data.Hex.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carcattone_data.Hex} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carcattone_data.Hex}
 */
proto.carcattone_data.Hex.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.carcattone_data.HexType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new proto.carcattone_data.Coord;
      reader.readMessage(value,proto.carcattone_data.Coord.deserializeBinaryFromReader);
      msg.setCoord(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carcattone_data.Hex.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carcattone_data.Hex.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carcattone_data.Hex} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carcattone_data.Hex.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCoord();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.carcattone_data.Coord.serializeBinaryToWriter
    );
  }
};


/**
 * optional HexType Type = 1;
 * @return {!proto.carcattone_data.HexType}
 */
proto.carcattone_data.Hex.prototype.getType = function() {
  return /** @type {!proto.carcattone_data.HexType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.carcattone_data.HexType} value */
proto.carcattone_data.Hex.prototype.setType = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional Coord coord = 2;
 * @return {?proto.carcattone_data.Coord}
 */
proto.carcattone_data.Hex.prototype.getCoord = function() {
  return /** @type{?proto.carcattone_data.Coord} */ (
    jspb.Message.getWrapperField(this, proto.carcattone_data.Coord, 2));
};


/** @param {?proto.carcattone_data.Coord|undefined} value */
proto.carcattone_data.Hex.prototype.setCoord = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.carcattone_data.Hex.prototype.clearCoord = function() {
  this.setCoord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.carcattone_data.Hex.prototype.hasCoord = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * @enum {number}
 */
proto.carcattone_data.HexType = {
  NONE: 0,
  RIVER: 1,
  MOUNTAIN: 2,
  PASTURE: 3,
  WHEATFIELD: 4,
  FOREST: 5,
  SEA: 6,
  DESERT: 7,
  HEXFROMBAG: 8
};

goog.object.extend(exports, proto.carcattone_data);
